version: "2"

services:
  notebook:
    build: .
    image: nb
    # image: jupyter/datascience-notebook
    container_name: nb
    volumes:
     - ".:/home/jovyan/work"
     # - "work:/home/jovyan/work"
    ports:
      - "80:8888"
    restart: always


# volumes:
#   work:
#     external:
#       name: ${WORK_VOLUME}
